@apiUrl = "http://localhost:7575/v1"
@sessionToken = ""

### Testing base project setup
GET {{apiUrl}}

### Testing clerk-protected endpoint
GET {{{{apiUrl}}}}/clerk-protected
Authorization: Bearer {{sessionToken}}